import { Ionicons } from "@expo/vector-icons";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import { ScrollView, Text, View, StyleSheet, Pressable } from "react-native";
import { colors } from "../constants/theme";
import { IconButton } from "../components/IconButton";
import { PostCard } from "../components/PostCard";
import { useRouter } from "expo-router";
import { BottomNav, useBottomNavVisibility } from "../components/BottomNav";

export default function Community(){const router=useRouter();const {visibility,onScroll}=useBottomNavVisibility();return <SafeAreaProvider><SafeAreaView style={s.safe}><View style={s.root}><ScrollView contentContainerStyle={s.content} onScroll={onScroll} scrollEventThrottle={16}><View style={s.head}><Text style={s.title}>Community</Text><View style={s.icons}><IconButton name="search-outline"/><IconButton name="create-outline"/></View></View><View style={s.tabs}><Text style={[s.tab,s.active]}>For You</Text><Text style={s.tab}>Following</Text></View><Pressable style={s.compose}><View style={s.avatar}><Ionicons name="person" size={17} color={colors.muted}/></View><Text style={s.placeholder}>What's happening in tech?</Text><Ionicons name="image-outline" size={20} color={colors.muted}/></Pressable><PostCard name="Kwame Repairs" handle="@kwamerepairs" text="Board repair today. Found a short on the power rail — sharing the diagnosis process for anyone learning microsoldering." image="https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1000&q=85"/><PostCard name="K-Tech Mobile" handle="@ktechmobile" text="Three clean iPhone 15 Pro units just arrived. Verified stock, 12-month warranty." image="https://images.unsplash.com/photo-1592286927505-2fd0b2b8b0a4?auto=format&fit=crop&w=1000&q=85"/></ScrollView><BottomNav active="community" visibility={visibility}/></View></SafeAreaView></SafeAreaProvider>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},root:{flex:1},content:{paddingHorizontal:18,paddingBottom:118},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingTop:8},title:{fontSize:25,fontWeight:"800",letterSpacing:-.6},icons:{flexDirection:"row",gap:8},tabs:{flexDirection:"row",gap:28,borderBottomWidth:1,borderBottomColor:colors.line,marginTop:18},tab:{paddingBottom:12,fontSize:14,fontWeight:"700",color:colors.muted},active:{color:colors.ink,borderBottomWidth:2,borderBottomColor:colors.ink},compose:{height:64,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:colors.line},avatar:{width:38,height:38,borderRadius:19,backgroundColor:colors.soft,alignItems:"center",justifyContent:"center"},placeholder:{flex:1,color:colors.muted,fontSize:14}})
