import { Ionicons } from "@expo/vector-icons";
import { SafeAreaView, ScrollView, Text, View, StyleSheet, Image, Pressable } from "react-native";
import { colors, radius } from "../constants/theme";
import { Chip } from "../components/Chip";
import { IconButton } from "../components/IconButton";
import { useRouter } from "expo-router";

const tutorials=[["How to diagnose an iPhone with no power","12 min · Intermediate","GH₵25","https://images.unsplash.com/photo-1581092919535-7146ff8fce9b?auto=format&fit=crop&w=1000&q=85"],["Charging IC diagnosis","18 min · Advanced","GH₵35","https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=85"],["Screen replacement basics","9 min · Beginner","Free","https://images.unsplash.com/photo-1603899122634-f086ca5f5ddd?auto=format&fit=crop&w=1000&q=85"]];
export default function Learn(){const router=useRouter();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.head}><Text style={s.title}>Learn</Text><IconButton name="bookmark-outline"/></View><Text style={s.sub}>Learn from verified repairers.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginTop:18}}><Chip label="Featured" active/><Chip label="Beginner"/><Chip label="Board repair"/><Chip label="Software"/></ScrollView><Pressable style={s.feature}><Image source={{uri:tutorials[0][3]}} style={s.featureImg}/><View style={s.featureCopy}><Text style={s.kicker}>FEATURED</Text><Text style={s.featureTitle}>{tutorials[0][0]}</Text><Text style={s.meta}>By Kwame Repairs ✓  ·  1.2K learners</Text><View style={s.watch}><Ionicons name="play" size={13} color="#fff"/><Text style={s.watchText}>Watch tutorial</Text></View></View></Pressable><Text style={s.section}>Popular tutorials</Text>{tutorials.slice(1).map(t=><View style={s.row} key={t[0]}><Image source={{uri:t[3]}} style={s.thumb}/><View style={{flex:1}}><Text style={s.tName}>{t[0]}</Text><Text style={s.meta}>{t[1]}</Text><Text style={s.price}>{t[2]}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},content:{padding:18,paddingBottom:40},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:26,fontWeight:"800",letterSpacing:-.7},sub:{fontSize:14,color:colors.muted,marginTop:5},feature:{height:285,borderRadius:radius.xl,overflow:"hidden",marginTop:20},featureImg:{width:"100%",height:"100%"},featureCopy:{position:"absolute",left:18,right:18,bottom:18},kicker:{fontSize:10,color:"#fff",fontWeight:"800",letterSpacing:1.2},featureTitle:{fontSize:24,lineHeight:29,color:"#fff",fontWeight:"800",marginTop:5},meta:{fontSize:12,color:colors.muted,marginTop:6},watch:{marginTop:12,alignSelf:"flex-start",backgroundColor:colors.accent,borderRadius:15,paddingHorizontal:13,paddingVertical:9,flexDirection:"row",gap:6,alignItems:"center"},watchText:{color:"#fff",fontWeight:"800",fontSize:12},section:{fontSize:20,fontWeight:"800",marginTop:26,marginBottom:12},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},thumb:{width:104,height:78,borderRadius:14},tName:{fontSize:14,fontWeight:"750",lineHeight:19,color:colors.ink},price:{fontSize:13,fontWeight:"800",color:colors.ink,marginTop:6}})
