import { Ionicons } from "@expo/vector-icons";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import { ScrollView, Text, View, StyleSheet, Image, Pressable } from "react-native";
import { colors, radius } from "../constants/theme";
import { IconButton } from "../components/IconButton";
import { BottomNav, useBottomNavVisibility } from "../components/BottomNav";

export default function Profile(){const {visibility,onScroll}=useBottomNavVisibility();return <SafeAreaProvider><SafeAreaView style={s.safe}><View style={s.root}><ScrollView contentContainerStyle={s.content} onScroll={onScroll} scrollEventThrottle={16}><View style={s.head}><Text style={s.title}>Profile</Text><IconButton name="settings-outline"/></View><View style={s.profile}><Image source={{uri:"https://i.pravatar.cc/160?img=12"}} style={s.avatar}/><View style={s.nameRow}><Text style={s.name}>Your Name</Text><View style={s.badge}><Text style={s.badgeText}>✓</Text></View></View><Text style={s.handle}>@yourhandle</Text><Text style={s.bio}>Phone enthusiast · Customer · Future repairer</Text><View style={s.stats}><Stat n="12" l="Posts"/><Stat n="48" l="Saved"/><Stat n="6" l="Orders"/></View></View><Pressable style={s.join}><View style={s.joinIcon}><Ionicons name="construct-outline" size={21}/></View><View style={{flex:1}}><Text style={s.joinTitle}>Join as a repairer or vendor</Text><Text style={s.joinSub}>Get jobs, sell products and publish tutorials.</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted}/></Pressable>{["Orders","My learning","Saved posts","Payment methods","Help & support"].map((x,i)=><View key={x} style={s.item}><View style={s.itemIcon}><Ionicons name={["bag-outline","play-circle-outline","bookmark-outline","card-outline","help-circle-outline"][i] as any} size={19}/></View><Text style={s.itemText}>{x}</Text><Ionicons name="chevron-forward" size={17} color={colors.muted}/></View>)}</ScrollView><BottomNav active="profile" visibility={visibility}/></View></SafeAreaView></SafeAreaProvider>}
function Stat({n,l}:{n:string;l:string}){return <View style={{alignItems:"center"}}><Text style={s.statN}>{n}</Text><Text style={s.statL}>{l}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},root:{flex:1},content:{padding:18,paddingBottom:118},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},title:{fontSize:26,fontWeight:"800"},profile:{alignItems:"center",paddingVertical:20},avatar:{width:88,height:88,borderRadius:44},nameRow:{flexDirection:"row",alignItems:"center",marginTop:12},name:{fontSize:21,fontWeight:"800"},badge:{width:18,height:18,borderRadius:9,backgroundColor:colors.blue,alignItems:"center",justifyContent:"center",marginLeft:5},badgeText:{color:"#fff",fontSize:10,fontWeight:"800"},handle:{fontSize:13,color:colors.muted,marginTop:3},bio:{fontSize:13,color:colors.muted,marginTop:9},stats:{flexDirection:"row",gap:45,marginTop:17},statN:{fontSize:16,fontWeight:"800"},statL:{fontSize:11,color:colors.muted,marginTop:2},join:{padding:15,borderRadius:18,backgroundColor:colors.accentSoft,flexDirection:"row",alignItems:"center",gap:11,marginBottom:15},joinIcon:{width:40,height:40,borderRadius:14,backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},joinTitle:{fontSize:14,fontWeight:"800"},joinSub:{fontSize:12,color:colors.muted,marginTop:3},item:{height:62,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:colors.line},itemIcon:{width:38,height:38,borderRadius:13,backgroundColor:colors.soft,alignItems:"center",justifyContent:"center"},itemText:{flex:1,fontSize:14,fontWeight:"700"}})
